// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPlantFeelingChange();
void onRgbColorChange();
void onRelay1Change();
void onRelay2Change();
void onUpdateDisplayChange();

String plant_feeling;
float humidity;
float temperature;
CloudColoredLight rgbColor;
int light;
int moistValue;
bool relay_1;
bool relay_2;
bool updateDisplay;

void initProperties(){

  ArduinoCloud.addProperty(plant_feeling, READWRITE, ON_CHANGE, onPlantFeelingChange);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(rgbColor, READWRITE, ON_CHANGE, onRgbColorChange);
  ArduinoCloud.addProperty(light, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(moistValue, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(relay_1, READWRITE, ON_CHANGE, onRelay1Change);
  ArduinoCloud.addProperty(relay_2, READWRITE, ON_CHANGE, onRelay2Change);
  ArduinoCloud.addProperty(updateDisplay, READWRITE, ON_CHANGE, onUpdateDisplayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
