// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onResetCounterChange();

float gyro_y;
int counter;
bool doorChange;
bool reset_counter;

void initProperties(){

  ArduinoCloud.addProperty(gyro_y, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(doorChange, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(reset_counter, READWRITE, ON_CHANGE, onResetCounterChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
