// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessageChange();
void onRgbChange();
void onScreenColorChange();
void onSoundDurationChange();
void onSoundFrequencyChange();
void onTextSizeChange();
void onChallengeFunctionChange();
void onSoundOnChange();
void onWarningAlarmChange();

String message;
CloudColoredLight rgb;
int screenColor;
int soundDuration;
int soundFrequency;
int textSize;
bool challenge_function;
bool soundOn;
bool warningAlarm;

void initProperties(){

  ArduinoCloud.addProperty(message, READWRITE, ON_CHANGE, onMessageChange);
  ArduinoCloud.addProperty(rgb, READWRITE, ON_CHANGE, onRgbChange);
  ArduinoCloud.addProperty(screenColor, READWRITE, ON_CHANGE, onScreenColorChange);
  ArduinoCloud.addProperty(soundDuration, READWRITE, ON_CHANGE, onSoundDurationChange);
  ArduinoCloud.addProperty(soundFrequency, READWRITE, ON_CHANGE, onSoundFrequencyChange);
  ArduinoCloud.addProperty(textSize, READWRITE, ON_CHANGE, onTextSizeChange);
  ArduinoCloud.addProperty(challenge_function, READWRITE, ON_CHANGE, onChallengeFunctionChange);
  ArduinoCloud.addProperty(soundOn, READWRITE, ON_CHANGE, onSoundOnChange);
  ArduinoCloud.addProperty(warningAlarm, READWRITE, ON_CHANGE, onWarningAlarmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
