/* 
  Sketch generated by the Arduino IoT Cloud Thing "Activity7"
  https://create.arduino.cc/cloud/things/ac5f7480-9669-42fc-afe0-db1fb60c85f1 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String results;
  int boardBeans;
  int boardGuess;
  int cloudBeans;
  int cloudGuess;
  bool boardBeans_Ready;
  bool boardGuess_Ready;
  bool cloudBeans_confirm;
  bool cloudGuess_confirm;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}






/*
  Since CloudBeans is READ_WRITE variable, onCloudBeansChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudBeansChange()  {
  // Add your code here to act upon CloudBeans change
}

/*
  Since CloudBeansConfirm is READ_WRITE variable, onCloudBeansConfirmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudBeansConfirmChange()  {
  // Add your code here to act upon CloudBeansConfirm change
}

/*
  Since CloudGuess is READ_WRITE variable, onCloudGuessChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudGuessChange()  {
  // Add your code here to act upon CloudGuess change
}

/*
  Since CloudGuessConfirm is READ_WRITE variable, onCloudGuessConfirmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudGuessConfirmChange()  {
  // Add your code here to act upon CloudGuessConfirm change
}