// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCloudBeansChange();
void onCloudGuessChange();
void onCloudBeansConfirmChange();
void onCloudGuessConfirmChange();

String results;
int boardBeans;
int boardGuess;
int cloudBeans;
int cloudGuess;
bool boardBeans_Ready;
bool boardGuess_Ready;
bool cloudBeans_confirm;
bool cloudGuess_confirm;

void initProperties(){

  ArduinoCloud.addProperty(results, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boardBeans, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boardGuess, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloudBeans, READWRITE, ON_CHANGE, onCloudBeansChange);
  ArduinoCloud.addProperty(cloudGuess, READWRITE, ON_CHANGE, onCloudGuessChange);
  ArduinoCloud.addProperty(boardBeans_Ready, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boardGuess_Ready, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloudBeans_confirm, READWRITE, ON_CHANGE, onCloudBeansConfirmChange);
  ArduinoCloud.addProperty(cloudGuess_confirm, READWRITE, ON_CHANGE, onCloudGuessConfirmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
